# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: root

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - "16.x"

    steps:
      - uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn build
